name: Pack Server Resources

on:
   workflow_dispatch:
   push:
      branches: [main]
      paths: [resources/**]

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
           with:
              submodules: recursive
              token: ${{ secrets.PTA }}

         - uses: actions/setup-node@v3

         - name: Install node_modules
           run: yarn
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - run: yarn run build && yarn run data
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - name: Commit ZIP File
           uses: EndBug/add-and-commit@v9
           with:
              add: server-resources.zip
              default_author: github_actions
              message: Updated server-resources.zip
